import type { Metadata } from "next";
import { Abel  } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const abelFont = Abel({ weight: "400", style: 'normal', subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Link href="/auth">Auth Page</Link>
      <body className={abelFont.className}>{children}</body>
    </html>
  );
}
